version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    healthcheck:
      # Use CMD-SHELL so we can run a pipeline; previous array form split the shell tokens
      test: ["CMD-SHELL", "echo ruok | nc 127.0.0.1 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:3
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
  - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.21.243.125:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_BROKER_ID=1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
