# Local profile for testing with docker-compose (lab PC as broker)
kafka:
  bootstrap_servers:
    - "172.21.243.125:9092"

  topics:
    cp_register: "cp-register"
    cp_register_ack: "cp-register-ack"
    auth_request: "auth-request"
    auth_response: "auth-response"
    cp_commands: "cp-commands"
    telemetry: "telemetry"
    health: "health"
    session_finished: "session-finished"

roles:
  central:
    consumer_topics:
      - "cp_register"
      - "auth_request"
      - "telemetry"
      - "health"
    producer_topics:
      - "cp_register_ack"
      - "auth_response"
      - "session_finished"
      - "cp_commands"
    consumer_group: "central-group"

  cp_engine:
    consumer_topics:
      - "cp_register_ack"
      - "cp_commands"
    producer_topics:
      - "cp_register"
      - "telemetry"
      - "health"
    consumer_group_template: "cp-{cp_id}-group"

  driver:
    consumer_topics:
      - "auth_response"
      - "session_finished"
    producer_topics:
      - "auth_request"
    consumer_group_template: "driver-{driver_id}-group"
